### ISSUE TITLE
CORS error when loading schema from GraphQL Code Generator

### ISSUE THREAD

**Issue by vgarmes** [benawad/lireddit#46]
I kept getting CORS errors when GraphQL Code Generator tries to load the schema. In the end I solved the issue by adding `Origin: 'http://localhost:3000'` to the schema request headers so my `codegen.yml` file looks like this:

```
overwrite: true
schema: 
  - 'http://localhost:4000/graphql':
      headers:
        Origin: 'http://localhost:3000'
documents: 'src/graphql/**/*.graphql'
generates:
  src/generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-urql'
```

Does anyone know a better solution?
